import { AppConfig } from './types';

export const DEFAULT_CONFIG: AppConfig = {
  branding: {
    logoUrl: 'https://daysemrodrigues.com.br/wp-content/uploads/2025/06/1.png',
    bgGradientTop: '#1E1E1E',
    bgGradientBottom: '#1E1E1E',
    textColor: '#FFFFFF',
    accentColor: '#D4A553',
    googleFontFamily: 'Mulish',
    titleFontSizePx: 36,
    bodyFontSizePx: 16,
  },
  content: {
    headerTitle: 'Diagnóstico de Diversidade & Inclusão',
    headerSubtitle: 'Descubra os pontos fortes e as áreas de melhoria da sua organização com nossa ferramenta de autodiagnóstico.',
    footerContent: 'Ubuntu: Consultoria em Diversidade e Inclusão com Dayse Rodrigues.',
  },
  buttons: {
    start: 'Começar Diagnóstico',
    next: 'Avançar',
    results: 'Ver Resultados',
    no: 'Não, obrigado',
    yes: 'Sim, quero ajuda',
    submitLead: 'Enviar e Falar com Consultor',
  },
  integrations: {
    whatsappNumber: '+5581997986524',
    webhookUrl: '',
    showPdfExport: true,
  },
  questions: {
    Pessoa: [
      "Sinto que minha identidade é respeitada no ambiente de trabalho.",
      "Tenho oportunidades iguais de crescimento profissional.",
      "Consigo expressar minhas opiniões sem medo de retaliação.",
      "A liderança demonstra um compromisso visível com a D&I.",
      "Existem canais seguros para relatar casos de discriminação.",
      "Sinto que faço parte de uma equipe diversa e inclusiva.",
      "As políticas da empresa apoiam ativamente a diversidade.",
      "Recebo feedbacks construtivos que me ajudem a crescer.",
      "O processo de contratação e promoção é transparente e justo.",
      "Sinto-me psicologicamente seguro para ser eu mesmo(a).",
    ],
    Empresa: [
      "Temos um comitê ou responsável formal por D&I.",
      "Realizamos treinamentos regulares sobre vieses inconscientes.",
      "Nossas lideranças são metricamente avaliadas por metas de D&I.",
      "A comunicação interna e externa reflete nosso compromisso com a diversidade.",
      "Oferecemos benefícios flexíveis que atendem a diferentes necessidades.",
      "Nossos processos de recrutamento buscam ativamente grupos sub-representados.",
      "Analisamos dados de demografia e equidade salarial regularmente.",
      "Temos grupos de afinidade (ERGs) ativos e com apoio institucional.",
      "Nossos espaços físicos e digitais são acessíveis a todos.",
      "O feedback dos colaboradores sobre D&I é coletado e levado a sério.",
    ],
    Escola: [
      "O currículo escolar inclui múltiplas perspectivas e culturas.",
      "O corpo docente reflete a diversidade do corpo discente.",
      "Promovemos ativamente um ambiente seguro contra bullying e discriminação.",
      "Os materiais didáticos são revistos para evitar estereótipos.",
      "Existem programas de apoio para alunos de grupos minorizados.",
      "As famílias são envolvidas em iniciativas de diversidade e inclusão.",
      "Os alunos têm voz ativa na construção de uma escola mais inclusiva.",
      "Oferecemos treinamento contínuo sobre D&I para todos os educadores.",
      "As políticas da escola são claras e inclusivas para todos os gêneros e identidades.",
      "O espaço físico da escola é acessível para pessoas com deficiência.",
    ],
  },
  diagnosisCopy: {
    low: 'Sua pontuação indica que já existem boas práticas de D&I em andamento, mas há espaço para aprimoramento contínuo.',
    medium: 'Sua pontuação sugere uma necessidade moderada de atenção. Existem fragilidades que podem impactar o clima e a equidade se não forem tratadas.',
    high: 'Sua pontuação indica uma alta urgência. É crucial desenvolver um plano de ação estratégico para mitigar riscos e construir um ambiente verdadeiramente inclusivo.',
    conclusionDefault: 'Este é um diagnóstico inicial. Para um plano de ação detalhado e personalizado, recomendamos uma conversa com nossos especialistas.',
  },
ai: {
    enabled: true,
    model: 'gemini-2.5-flash',
    apiKey: 'COLE_SUA_CHAVE_API_RESTRITA_AQUI', // AVISO: Esta chave ficará publicamente visível no código do site.
  },
  version: '1.0.1',
};